final List<Map<String, String>> departamentos = [
    {'name': 'Boaco', 'placeId': 'ChIJ2coa6RWhc48RYOiFRtjrwQw'},
    {'name': 'Carazo', 'placeId': 'ChIJXx8sSk8ddI8RU9GmileemrA'},
    {'name': 'Chinandega', 'placeId': 'ChIJP-zXMuzxcI8R7AKWj1Oh4FM'},
    {'name': 'Chontales', 'placeId': 'ChIJX1T9kOljc48RYZWF6uLkKl8'},
    {'name': 'Estelí', 'placeId': 'ChIJrcELwEKMcY8Rb0qVUrMa3pA'},
    {'name': 'Granada', 'placeId': 'ChIJkxVrcJEMdI8RjLTOyE2QjDs'},
    {'name': 'Jinotega', 'placeId': 'ChIJif9XzIg-co8RypZkVTUQu7k'},
    {'name': 'León', 'placeId': 'ChIJd3qPu5IfcY8RPDHqZG_AtTo'},
    {'name': 'Madriz', 'placeId': 'ChIJAWZ_HNXfcY8Rh2uztwRPfpU'},
    {'name': 'Managua', 'placeId': 'ChIJC4gH2Q1WcY8RakxPFKL0Xmw'},
    {'name': 'Masaya', 'placeId': 'ChIJKRUckR0GdI8R0moxUGHN1vI'},
    {'name': 'Matagalpa', 'placeId': 'ChIJLx1W-TBIco8RmdvMt22kkxc'},
    {'name': 'Nueva Segovia', 'placeId': 'ChIJI33IspbkbY8RjIUDRc8qzOE'},
    {'name': 'Rivas', 'placeId': 'ChIJUyYgT8FOdI8RkYf6J6WKeps'},
    {'name': 'Río San Juan', 'placeId': 'ChIJb7BGK67NCo8Rcq6oxf7JuP0'},
    {'name': 'RAAN', 'placeId': 'ChIJ828chdnkEI8RfB3WTR7D8Do'},
    {'name': 'RAAS', 'placeId': 'ChIJ6chW8QYIDI8RpB4DOlSmD1k'},
  ];